before_install:
  - sudo apt-get -qq update
  - sudo apt-get install curl libcurl4-openssl-dev
  - sudo apt-get install build-essential
  - sudo apt-get install automake
  - sudo apt-get install bison flex
  - sudo apt-get install libcurl4-gnutls-dev
  - sudo apt-get install autotools-dev
  - sudo apt-get install libboost-dev
  - git clone https://github.com/miloyip/rapidjson.git /tmp/rapidjson
  - cd /tmp/rapidjson
  - ./configure
  - make && make install



  - git clone https://github.com/JinpengLI/gsoap.git /tmp/gsoap
  - cd /tmp/gsoap
  - aclocal
  - autoheader
  - automake --add-missing
  - autoconf
  - automake
  - ./configure
  - make && make install


language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make

